server:
  port: 8082

spring:
  application:
    name: api-gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: api-gateway-service




